# Parameters to run the FKMOD cell types for mouse atrial and SAN cells.
# Jan 22, 2013.
# SK

# atrial AP.
atrial: fk0_atrial.bbs
	Beatbox_SEQ fk0_atrial.bbs

# this is the input for mice5.
san:	fk0_san.bbs
	Beatbox_SEQ fk0_san.bbs 5 0.05 115 45 16.5 16.5 12000 75 1.5 400 0.2 0.5 0.01 2.5 2.0 1.0 1.2 1.5 1.1 0.01 11.0 0.15 5.0 50.0 35.0
