/**
 * Copyright (C) (2010-2016) Vadim Biktashev, Irina Biktasheva et al. 
 * (see ../AUTHORS for the full list of contributors)
 *
 * This file is part of Beatbox.
 *
 * Beatbox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Beatbox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Beatbox.  If not, see <http://www.gnu.org/licenses/>.
 */

/* Header for module STUNIT2, generated by p2c */
#ifndef STUNIT2_H
#define STUNIT2_H

extern void DATAIN(void);
extern void STANDARD(void);
extern void PURKINJE(void);
extern void SINUS(void);
extern void SINSIN(void);
extern void HATRIUM(void);
extern void SINAT(void);
extern void VENTRICLE(void);
extern void RATVCELL(void);
extern void GPCELL(void);
extern void FROGSINUS(void);
extern void ATRIUM(void);

#endif /*STUNIT2_H*/
